added exclude_h1 option to remove highest layer of numbering
timvink/mkdocs-enumerate-headings-plugin pull request #39
Opened 2023-11-23 16:07 UTC by TimChaubet-I4U

We've added the `exclude_h1` boolean option to exclude the highest layer of numbering from output.
In case you only have one (or a few) header level 1 titles, and you don't want this layer to be numbered, you can set this to true.

So if you set in the yaml:
``` yaml
plugins:
  - enumerate-headings: 
      toc_depth: 6
      strict: false
      increment_across_pages: false
      exclude_h1: true
```

These markdown titles ...
``` markdown
# Top Layer Title
## subA
### someother title
## subB
```

will translate to

# Top Layer Title
## 1. subA
### 1.2 someother title
## 2. subB

2023-11-23 19:30 UTC, timvink requested changes
Looks good, open to adding this!

Please remove the unnecessary comments. It would also be great if you could include a unit test to ensure this works (and keeps working in the future)

2023-11-23 19:30 UTC, timvink commented on README.md
> +- **`exclude_h1` (default false) exclude the header_1 titles from getting numbered. Header2 titles will get 1, 2, 3. Header3 titles will get 1.1, 1.2, 2.1, 3.1, 3.2, 3.3, 3.4 etc ...
Add backticks to variables, like so \`false\`  to render like `false`

2023-11-23 19:30 UTC, timvink commented on mkdocs_enumerate_headings_plugin/heading.py
> +
Remove comment

2023-11-23 19:30 UTC, timvink commented on mkdocs_enumerate_headings_plugin/heading.py
> +    # def enumerate(self, add_span_element=False
remove comment

2023-11-23 19:30 UTC, timvink commented on mkdocs_enumerate_headings_plugin/heading.py
> +    def enumerate(self, add_span_element=False, exclude_h1=False): # custom exclude_h1
also remove inline comment

2023-11-23 19:30 UTC, timvink commented on mkdocs_enumerate_headings_plugin/plugin.py
> +        htmlpage.enumerate_headings(exclude_h1=self.config.get("exclude_h1")) # custom exclude_h1
remove inline comment

2023-11-23 19:38 UTC, timvink commented
Actually this might be done simpler.. you can try using the `on_post_page()` event like here:

https://github.com/timvink/mkdocs-enumerate-headings-plugin/pull/36/files#r1403687795

2023-11-24 08:58 UTC, TimChaubet-I4U reviewed
I removed redundant comments & beautified the readme.md line
To be honest, I'm not sure what you are aiming at when you mention the on_post event. Could you elaborate a bit more?

2024-05-02 11:08 UTC, closed without merging